In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split 
from sklearn.ensemble import RandomForestClassifier 
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('daten.csv')

In [3]:
y = df["win"]
X = df.drop("win", axis=1) 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
df.head(5)

,id,matchid,player,name,adjposition,team_role,win,championid,kills,deaths,...,visionscore,firstblood,neutralminionskilled,ownjunglekills,enemyjunglekills,totcctimedealt,champlvl,duration,platformid,seasonid
0,9,10,1,124,3,3,0.0,19,6.0,10.0,...,14.0,0.0,69.0,42.0,27.0,610.0,13.0,1909,1,8
1,10,10,2,72,2,2,0.0,267,0.0,2.0,...,30.0,0.0,1.0,1.0,0.0,211.0,14.0,1909,1,8
2,11,10,3,22,1,1,0.0,119,7.0,8.0,...,26.0,0.0,3.0,1.0,2.0,182.0,14.0,1909,1,8
3,12,10,4,28,5,5,0.0,114,5.0,11.0,...,5.0,0.0,6.0,6.0,0.0,106.0,15.0,1909,1,8
4,13,10,5,121,4,4,0.0,112,2.0,8.0,...,15.0,0.0,4.0,3.0,1.0,159.0,15.0,1909,1,8

In [5]:
# Import the necessary libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Create a random forest classifier
rf = RandomForestClassifier(random_state=42)

# Fit the classifier to the training data
rf.fit(X_train, y_train)

# Predict the labels of the test data
y_pred = rf.predict(X_test)

# Compute and print the accuracy score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.8619

In [7]:
# Print out the feature importance
importance = rf.feature_importances_